### ISSUE TITLE
Possible not to prepend at all?

### ISSUE THREAD

**Issue by evelyn** [aherrmann/jekyll_style_urls_with_hakyll_examples#1]
https://github.com/aherrmann/jekyll_style_urls_with_hakyll_examples/blob/master/site.hs#L99

Wondering if it's possible to edit this in such a way where the category is **not** prepended?

**For example:** http://www.example.com/posts/2015/02/02/category/post-title/

**Comment by aherrmann** [comment]
That's definitely possible. Commit a7b86b66363e865bb498c3bb52e7297649ae99b6 demonstrates that. Unfortunately, it mixes up the date and category parts of the URL. However, it seems to do the job. (I haven't done any thorough testing). URLs as in your example are generated in the branch [category_after_date](https://github.com/aherrmann/jekyll_style_urls_with_hakyll_examples/tree/category_after_date).

**Comment by evelyn** [comment]
Hi! Everything was working great up until about a month or so ago...

Suddenly I'm getting

> berkson.github.io/source/blog.hs: 333, 42
> • Couldn't match type ‘unordered-containers-0.2.7.1:Data.HashMap.Base.HashMap
>                          text-1.2.2.1:Data.Text.Internal.Text
>                          aeson-0.11.2.0:Data.Aeson.Types.Internal.Value’
>                  with ‘M.Map [Char] [Char]’
>   Expected type: M.Map [Char] [Char]
>     Actual type: Metadata
> • In the first argument of ‘(M.!)’, namely ‘md’
>   In the first argument of ‘(++)’, namely ‘(md M.! "author")’
>   In the second argument of ‘(++)’, namely ‘(md M.! "author") ++ "/"’

On my own rework of your code. :(

> directorizeDateAndAuthor :: Routes
> directorizeDateAndAuthor = metadataRoute $ \md ->
>     gsubRoute "/[0-9]{4}-[0-9]{2}-[0-9]{2}-" $ \s ->
>         replaceAll "-" (const "/") s ++ (md M.! "author") ++ "/"

I was wondering if you'd mind helping me decipher what exactly it's telling me?

Ref: https://github.com/berkson/berkson.github.io/blob/source/source/blog.hs#L330

**Comment by luckypoem** [comment]
@berkson 

hi,i also encounter the error:
root@AR:/usr/local/hakyll_examples-site# ls
about.rst	  hakyll-extensionless-urls.cabal  posts      templates
contact.markdown  images			   README.md
css		  index.html			   site.hs
root@AR:/usr/local/hakyll_examples-site# ghc --make site.hs
[1 of 1] Compiling Main             ( site.hs, site.o )

site.hs:101:6: error:
    • Couldn't match type ‘unordered-containers-0.2.7.1:Data.HashMap.Base.HashMap
                             Data.Text.Internal.Text
                             aeson-0.11.2.1:Data.Aeson.Types.Internal.Value’
                     with ‘M.Map [Char] FilePath’
      Expected type: M.Map [Char] FilePath
        Actual type: Metadata
    • In the first argument of ‘(M.!)’, namely ‘md’
      In the first argument of ‘(</>)’, namely ‘md M.! "category"’
      In the first argument of ‘(.)’, namely ‘(md M.! "category" </>)’
root@AR:/usr/local/hakyll_examples-site#

how to fix it?
thank u all.

**Comment by aherrmann** [comment]
The type behind `Metadata` was changed in the Hakyll package. Instead of using the `Map` functions Hakyll exports [its own lookup functions](http://hackage.haskell.org/package/hakyll-4.8.3.2/docs/Hakyll-Core-Metadata.html). You can see an example [here](https://github.com/aherrmann/aherrmann.github.io.hakyll/blob/master/src/Main.hs#L168-L172) and [here](https://github.com/aherrmann/jekyll_style_urls_with_hakyll_examples/blob/category_after_date/site.hs#L86-L91).

Note, that I've also changed this example repository to use [stack](https://docs.haskellstack.org/en/stable/README/). You might want to do the same thing for your own site to avoid random breakage after updates.

Unfortunately, I don't have time to look into these issues very often. [Stackoverflow](http://stackoverflow.com/) might be a better place to ask these types of questions.
